import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({ baseDirectory: import.meta.dirname });

const config = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    // `next-env.d.ts` is generated by Next on every build, and `public/` holds
    // static assets — neither is ours to fix.
    ignores: [
      ".next/**",
      "node_modules/**",
      "prisma/migrations/**",
      "data/**",
      "storage/**",
      "public/**",
      "next-env.d.ts",
    ],
  },
  {
    rules: {
      // The seed and export layers pass Prisma payloads around; the generated
      // types are precise enough that a blanket ban buys nothing here.
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },
];

export default config;
